language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381908-1_Myasnikova_lab3_4
  - make -j
  - ./test/MP2_TESTS
notifications:
  email: false
